version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: npm run dev
    volumes:
      - .:/app
      - backend_node_modules:/app/backend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    command: npm run dev
    volumes:
      - .:/app
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
